export const CustomerData = [
  {
    id: 1,
    name: "ARBEC",
    buyer: "VANESSA",
    lastName: "Mitchell",
    email: "vaness.mitchell@gmail.com",
    phone: "123 456 78910",
    message: [
      " Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus",
      "corporis doloribus quibusdam hic eius sed error",
      "architecto nulla natusfuga placeat eum praesentium",
      "labore inventore eaque nobis in nihil",
    ],
  },
  {
    id: 2,
    name: "Resolu",
    lastName: "Marion",
    buyer: "David",
    email: "davidboifor@delat.com",
    phone: "123 456 78910",
    message: [
      " Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus",
      "corporis doloribus quibusdam hic eius sed error",
      "architecto nulla natusfuga placeat eum praesentium",
      "labore inventore eaque nobis in nihil",
    ],
  },
  {
    id: 3,
    name: "COMTOIS",
    buyer: "Marc",
    lastName: "lapage",
    email: "marc@gmail.com",
    phone: "123 456 78910",
    message: [
      " Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus",
      "corporis doloribus quibusdam hic eius sed error",
      "architecto nulla natusfuga placeat eum praesentium",
      "labore inventore eaque nobis in nihil",
    ],
  },
  {
    id: 4,
    name: "CREATE",
    buyer: "GENEVIEVE",
    lastName: "Marion",
    email: "genevieve@gmail.com",
    phone: "123 456 78910",
    message: [
      " Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus",
      "corporis doloribus quibusdam hic eius sed error",
      "architecto nulla natusfuga placeat eum praesentium",
      "labore inventore eaque nobis in nihil",
    ],
  },
  {
    id: 5,
    name: "DAAQUM",
    buyer: "BABACAR",
    lastName: "Diakite",
    email: "babacar@gmail.com",
    phone: "123 456 78910",
    message: [
      " Lorem ipsum dolor sit amet consectetur adipisicing elit. Repellendus",
      "corporis doloribus quibusdam hic eius sed error",
      "architecto nulla natusfuga placeat eum praesentium",
      "labore inventore eaque nobis in nihil",
    ],
  },
];
