export const CustomerData = [
  {
    id: 1,
    company: "ARBEC",
    division: "parent",
    contact: [
      {
        name: "Marc",
        lastName: "lapage",
        email: "marc@gmail.com",
        phone: "123 456 78910",
        title: "buyer",
        message: [
          "obj 1",
          " Lorem ipsum dolor sit, amet consectetur adipisicing elit",
          "Laborevoluptatum delectus dolorum consectetur eum minima rem, sed, in itaque",
          "soluta expedita quas ipsum cumque quos suscipit quo doloremque iste aperiam",
        ],
      },
      {
        name: "David",
        lastName: "Marion",
        email: "davidc@gmail.com",
        phone: "123 456 78910",
        title: "mecanic",
        message: [
          "obj 2",
          " Lorem ipsum dolor sit, amet consectetur adipisicing elit",
          "Laborevoluptatum delectus dolorum consectetur eum minima rem, sed, in itaque",
          "soluta expedita quas ipsum cumque quos suscipit quo doloremque iste aperiam",
        ],
      },
      {
        name: "Babacar",
        lastName: "Diakite",
        email: "babacar@gmail.com",
        phone: "123 456 78910",
        title: "it",
        message: [
          "obj 3",
          " Lorem ipsum dolor sit, amet consectetur adipisicing elit",
          "Laborevoluptatum delectus dolorum consectetur eum minima rem, sed, in itaque",
          "soluta expedita quas ipsum cumque quos suscipit quo doloremque iste aperiam",
        ],
      },
    ],
  },
  {
    id: 2,
    company: "Resolu",
    division: "Ladore",
    contact: [
      {
        name: "Vanessa",
        lastName: "Mitchell",
        email: "vanessa@gmail.com",
        phone: "123 456 78910",
        title: "buyer",
        message: [
          "obj 4",
          " Lorem ipsum dolor sit, amet consectetur adipisicing elit",
          "Laborevoluptatum delectus dolorum consectetur eum minima rem, sed, in itaque",
          "soluta expedita quas ipsum cumque quos suscipit quo doloremque iste aperiam",
        ],
      },
      {
        name: "Christopher",
        lastName: "oullette",
        email: "christopher@gmail.com",
        phone: "123 456 78910",
        title: "mecanic",
        message: [
          "obj 5",
          " Lorem ipsum dolor sit, amet consectetur adipisicing elit",
          "Laborevoluptatum delectus dolorum consectetur eum minima rem, sed, in itaque",
          "soluta expedita quas ipsum cumque quos suscipit quo doloremque iste aperiam",
        ],
      },
      {
        name: "jean",
        lastName: "oullette",
        email: "babacar@gmail.com",
        phone: "123 456 78910",
        title: "it",
        message: [
          "obj 6",
          " Lorem ipsum dolor sit, amet consectetur adipisicing elit",
          "Laborevoluptatum delectus dolorum consectetur eum minima rem, sed, in itaque",
          "soluta expedita quas ipsum cumque quos suscipit quo doloremque iste aperiam",
        ],
      },
    ],
  },
  {
    id: 3,
    company: "Norboard",
    division: "lassar",
    contact: [
      {
        name: "Alex",
        lastName: "Black",
        email: "alex@gmail.com",
        phone: "123 456 78910",
        title: "buyer",
        message: [
          "obj 7",
          " Lorem ipsum dolor sit, amet consectetur adipisicing elit",
          "Laborevoluptatum delectus dolorum consectetur eum minima rem, sed, in itaque",
          "soluta expedita quas ipsum cumque quos suscipit quo doloremque iste aperiam",
        ],
      },
      {
        name: "John",
        lastName: "King",
        email: "john@gmail.com",
        phone: "123 456 78910",
        title: "mecanic",
        message: [
          "obj 8",
          " Lorem ipsum dolor sit, amet consectetur adipisicing elit",
          "Laborevoluptatum delectus dolorum consectetur eum minima rem, sed, in itaque",
          "soluta expedita quas ipsum cumque quos suscipit quo doloremque iste aperiam",
        ],
      },
      {
        name: "Krista",
        lastName: "Wilcox",
        email: "babacar@gmail.com",
        phone: "123 456 78910",
        title: "it",
        message: [
          "obj 9",
          " Lorem ipsum dolor sit, amet consectetur adipisicing elit",
          "Laborevoluptatum delectus dolorum consectetur eum minima rem, sed, in itaque",
          "soluta expedita quas ipsum cumque quos suscipit quo doloremque iste aperiam",
        ],
      },
    ],
  },
  {
    id: 4,
    company: "CREATE",
    division: "Lachine",
    contact: [
      {
        name: "Rose",
        lastName: "Marion",
        email: "rose@gmail.com",
        phone: "123 456 78910",
        title: "buyer",
        message: [
          "obj 10",
          " Lorem ipsum dolor sit, amet consectetur adipisicing elit 10",
          "Laborevoluptatum delectus dolorum consectetur eum minima rem, sed, in itaque 10",
          " 10soluta expedita quas ipsum cumque quos suscipit quo doloremque iste aperiam",
        ],
      },
      {
        name: "Stepjane",
        lastName: "Tramblay",
        email: "stephan@gmail.com",
        phone: "123 456 78910",
        title: "mecanic",
        message: [
          "obj 11",
          " Lorem ipsum dolor sit, amet consectetur adipisicing elit",
          "Laborevoluptatum delectus dolorum consectetur eum minima rem, sed, in itaque",
          "soluta expedita quas ipsum cumque quos suscipit quo doloremque iste aperiam",
        ],
      },
      {
        name: "Adala",
        lastName: "Said",
        email: "abdala@gmail.com",
        phone: "123 456 78910",
        title: "it",
        message: [
          "obj 12",
          " Lorem ipsum dolor sit, amet consectetur adipisicing elit",
          "Laborevoluptatum delectus dolorum consectetur eum minima rem, sed, in itaque",
          "soluta expedita quas ipsum cumque quos suscipit quo doloremque iste aperiam",
        ],
      },
    ],
  },
  {
    id: 5,
    company: "DAAQUM",
    division: "parent",
    contact: [
      {
        name: "Joely",
        lastName: "Graham",
        email: "joely@gmail.com",
        phone: "123 456 78910",
        title: "buyer",
        message: [
          "obj 13",
          " Lorem ipsum dolor sit, amet consectetur adipisicing elit",
          "Laborevoluptatum delectus dolorum consectetur eum minima rem, sed, in itaque",
          "soluta expedita quas ipsum cumque quos suscipit quo doloremque iste aperiam",
        ],
      },
      {
        name: "Ousmane",
        lastName: "Tangue",
        email: "ousmane@gmail.com",
        phone: "123 456 78910",
        title: "mecanic",
        message: [
          "obj 14",
          " Lorem ipsum dolor sit, amet consectetur adipisicing elit",
          "Laborevoluptatum delectus dolorum consectetur eum minima rem, sed, in itaque",
          "soluta expedita quas ipsum cumque quos suscipit quo doloremque iste aperiam",
        ],
      },
      {
        name: "Roxan",
        lastName: "Wilcox",
        email: "roxan@gmail.com",
        phone: "123 456 78910",
        title: "it",
        message: [
          "obj 15",
          " Lorem ipsum dolor sit, amet consectetur adipisicing elit",
          "Laborevoluptatum delectus dolorum consectetur eum minima rem, sed, in itaque",
          "soluta expedita quas ipsum cumque quos suscipit quo doloremque iste aperiam",
        ],
      },
    ],
  },
];
