export const CustomerData = [
  {
    id: 1,
    company: "ARBEC",
    division: "paren",
    contact: [
      {
        name: "Marc",
        lastName: "lapage",
        email: "marc@gmail.com",
        phone: "123 456 78910",
        title: "buyer",
      },
      {
        name: "David",
        lastName: "Marion",
        email: "davidc@gmail.com",
        phone: "123 456 78910",
        title: "mecanic",
      },
      {
        name: "Babacar",
        lastName: "Diakite",
        email: "babacar@gmail.com",
        phone: "123 456 78910",
        title: "it",
      },
    ],
  },
  {
    id: 2,
    company: "Resolu",
    division: "Ladore",
    contact: [
      {
        name: "Vanessa",
        lastName: "Mitchell",
        email: "vanessa@gmail.com",
        phone: "123 456 78910",
        title: "buyer",
      },
      {
        name: "Christopher",
        lastName: "oullette",
        email: "christopher@gmail.com",
        phone: "123 456 78910",
        title: "mecanic",
      },
      {
        name: "jean",
        lastName: "oullette",
        email: "babacar@gmail.com",
        phone: "123 456 78910",
        title: "it",
      },
    ],
  },
  {
    id: 3,
    company: "Norboard",
    division: "lassar",
    contact: [
      {
        name: "Alex",
        lastName: "Black",
        email: "alex@gmail.com",
        phone: "123 456 78910",
        title: "buyer",
      },
      {
        name: "John",
        lastName: "King",
        email: "john@gmail.com",
        phone: "123 456 78910",
        title: "mecanic",
      },
      {
        name: "Krista",
        lastName: "Wilcox",
        email: "babacar@gmail.com",
        phone: "123 456 78910",
        title: "it",
      },
    ],
  },
  {
    id: 4,
    company: "CREATE",
    division: "Lachine",
    contact: [
      {
        name: "Rose",
        lastName: "Marion",
        email: "rose@gmail.com",
        phone: "123 456 78910",
        title: "buyer",
      },
      {
        name: "Stepjane",
        lastName: "Tramblay",
        email: "stephan@gmail.com",
        phone: "123 456 78910",
        title: "mecanic",
      },
      {
        name: "Adala",
        lastName: "Said",
        email: "abdala@gmail.com",
        phone: "123 456 78910",
        title: "it",
      },
    ],
  },
  {
    id: 5,
    company: "DAAQUM",
    division: "parent",
    contact: [
      {
        name: "Joely",
        lastName: "Graham",
        email: "joely@gmail.com",
        phone: "123 456 78910",
        title: "buyer",
      },
      {
        name: "Ousmane",
        lastName: "Tangue",
        email: "ousmane@gmail.com",
        phone: "123 456 78910",
        title: "mecanic",
      },
      {
        name: "Roxan",
        lastName: "Wilcox",
        email: "roxan@gmail.com",
        phone: "123 456 78910",
        title: "it",
      },
    ],
  },
];
